config/routes.rb
Barcode::Application.routes.draw do
  root :to => 'home#index'
  resources :users, :only => [:new, :create]
  resources :session, :only => [:new, :create] do
    collection do
      delete :destroy
    end
  end
  resources :venues, :except => [:index, :show] do
    member do
      get "new_availabilities"
      post "create_availabilities"
    end
  end
  resources :availabilities, :only => [:edit, :update, :destroy]
  resources :pub_crawls do
    collection do
      get "end_times"
      post "invite_friends"
    end
    member do
      post "join_crawl"
    end
  end
  resources :stops, :only => [:create] do
    collection do
      post "num_stops"
    end
  end
  resources :activities, :only => [:create, :new]
  resources :check_ins, :only => [:create, :new] do
    collection do
      get "select_location"
    end
  end
  resources :responses, :only => [:create, :new]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @crawls = PubCrawl.all
    @venues = Venue.all
    @x = 4
  end
end

app/views/home/_mobile_content.html.haml
-if @cu.present? && @cu.is_owner == false
  =link_to(image_tag("checkin2.png"), "#", :id => "mobile_check_in_btn")
  =link_to(image_tag("challenge2.png"), new_response_path, :remote => true, :id => "mobile_response_button")
-elsif @cu.present? && @cu.is_owner
  %h1 Please sign in on a non-touch screen
-else
  #mobile_session
    = render 'session/mobile_form'

app/views/home/_owner_content.html.haml
-if @cu.present? && @cu.is_owner
  .row
    .large-6.columns
      #add{:style => "text-align:center; position:relative; top: 30px;"}
        =link_to(image_tag("add_bar_coaster2.png"), new_venue_path, :remote => true, :class => "login")
    .large-6.columns
      %h2.secondary_display.dashboard#dashboard Owner Dashboard
      %p.description From here, you can manage events at the venues you own.  Click the button to the left to add your bar to the BarCode roster.  Then, choose the dates and times you want to make your venue be available for events.
      %p.description Quinoa actually selvage, banjo locavore chambray brooklyn intelligentsia pitchfork high life gluten-free ugh mumblecore banh mi. Gastropub 90's ethical selfies raw denim, pug umami mixtape salvia keytar. Master cleanse photo booth street art tonx carles.
  / .row
  /   .large-5.large-centered.columns#venue_form

  .row
    .large-12.columns
      #my_venues
        = render 'venues/my_venues'

app/views/home/_regular_content.html.haml
-if @cu.present? && @cu.is_owner == false
  .row
    .large-4.columns
      #button{style:"text-align:center"}
        / =link_to("Check-in!", "#", :class => "button radius large expand", )
        =link_to(image_tag("checkin2.png"), "#", :class => 'login', :id => "checkin_btn")
    .large-4.columns
      =link_to(image_tag("create_crawl_coaster2.png"), new_pub_crawl_path, :class => 'login', :remote => true)
    .large-4.columns.login
      / = link_to("All Crawls", pub_crawls_path, :class => "button radius large expand", :remote => true)
      =link_to(image_tag("allcrawls2.png"), pub_crawls_path, :class => 'login', :remote => true)
  .row
    .large-12.columns
      #reg_content

app/views/home/index.html.haml
.row
  .large-12.columns.hide-for-touch#owner_content
    =render :partial => "home/owner_content"
/ .row
/   .large-12.columns
/     =render :partial => "stops/make_stops"

.row
  .large-12.columns.hide-for-touch#regular_content
    =render :partial => "home/regular_content"

.row
  .large-12.columns.show-for-touch#mobile_content
    = render :partial => "mobile_content"