config/routes.rb
Barcode::Application.routes.draw do
  root :to => 'home#index'
  resources :users, :only => [:new, :create]
  resources :session, :only => [:new, :create] do
    collection do
      delete :destroy
    end
  end
  resources :venues, :except => [:index, :show] do
    member do
      get "new_availabilities"
      post "create_availabilities"
    end
  end
  resources :availabilities, :only => [:edit, :update, :destroy]
  resources :pub_crawls do
    collection do
      get "end_times"
      post "invite_friends"
    end
    member do
      post "join_crawl"
    end
  end
  resources :stops, :only => [:create] do
    collection do
      post "num_stops"
    end
  end
  resources :activities, :only => [:create, :new]
  resources :check_ins, :only => [:create, :new] do
    collection do
      get "select_location"
    end
  end
  resources :responses, :only => [:create, :new]
end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  address    :string(255)
#  latitude   :float
#  longitude  :float
#  image      :string(255)
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Venue < ActiveRecord::Base
  attr_accessible :address, :image, :latitude, :longitude, :name, :user_id, :remote_image_url, :category_ids
  has_and_belongs_to_many :categories
  has_many :activities
  has_many :stops
  has_many :availabilities
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  mount_uploader :image, VenueImageUploader
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def new
    @venue = Venue.new
    @categories = Category.order(:name)
  end

  def create
    @venue = Venue.create(params[:venue])
    @cu.venues << @venue
    @user_type = "own"
  end

  def edit
    @venue = Venue.find(params[:id])
    @categories = Category.order(:name)
  end

  def update
    venue = Venue.find(params[:id])
    venue.update_attributes(params[:venue])
    venue.save
  end

  def destroy
    Venue.delete(params[:id])
  end

  def new_availabilities
    @venue = Venue.find(params[:id])
  end

  def create_availabilities
    dates = params[:dates].split(",")
    venue = Venue.find(params[:id])
    dates.each do |date|
      Availability.create(date:date, promotion:params[:promotion], venue_id:venue.id)
    end
    @venue = venue
  end


end

app/views/venues/_add_activity.html.haml
=form_tag activities_path, :remote => true do
  =hidden_field_tag :venue_id, @venue.id
  =hidden_field_tag :user_type, @user_type
  %p Enter a Challenge or Question
  =text_field_tag :question
  %label Should the response be a text or photo?
  .switch.small.round.small-3.small-centered
    %input#a{:name => "response_type", :type => "radio", :value => "t"}
    %label{:for => "a", :onclick => ""} Text
    %input#a1{:checked => "checked", :name => "response_type", :type => "radio", :value => "p"}
    %label{:for => "a1", :onclick => ""} Photo
    %span
  =submit_tag nil, :class => "button round small"

app/views/venues/_availabilities.html.haml
/ %table.venue_margin{:style => "width: 100%"}
/   %thead
/     %th.avail_head Date
/     %th.avail_head Promotion
/     %th
/     %th
/   -venue.availabilities.order(:date).each do |ava|
/     %tr
/       %td.avail= ava.date
/       %td.avail= ava.promotion
/       %td.schedule_btns= link_to("Edit", edit_availability_path(ava.id), :class => "schedule_btns", :remote => true, :class => "button round")
/       %td.schedule_btns= link_to("Delete", "/availabilities/#{ava.id}", :method => :delete, :remote => true, :confirm => "Are you sure you want to delete this availability?", :class => "button round success")

%ul.large-block-grid-4
  -venue.availabilities.order(:date).each do |ava|
    %li
      #ava.crawl_list
        %p= "Promotion: #{ava.promotion}"
        %p= "Date: #{ava.date}"
        .schedule_btns
          = link_to("Edit", edit_availability_path(ava.id), :class => "schedule_btns", :remote => true, :class => "button small round")
          = link_to("Delete", "/availabilities/#{ava.id}", :method => :delete, :remote => true, :confirm => "Are you sure you want to delete this availability?", :class => "button round small success")

app/views/venues/_form.html.haml
= form_for @venue, :html => {:multipart => true}, :remote => true do |f|
  %fieldset#new_venue
    %legend#new_venue_form_head= @venue.name.nil? ? "New Venue" : "#{@venue.name}"
    =f.text_field :name, :placeholder => 'name', :class => 'text_field'
    =f.text_field :address, :placeholder => 'address', :class => "text_field"
    =f.file_field :image
    =f.text_field :remote_image_url
    %p Select All Categories That Apply:
    %ul.large-block-grid-3
      -@categories.each do |cat|
        %li
          %span= check_box_tag("venue[category_ids][]", cat.id, cat.in?(@venue.categories))
          %span= cat.name
    =f.submit nil, :class => "button round small"

app/views/venues/_my_venues.html.haml
-@cu.venues.order(:name).each do |venue|
  .row.venue_panel
    .large-3.columns
      = image_tag(venue.image.thumb.url)
    .large-9.columns
      %h3.venue= venue.name
      %p.venue_info= venue.address
      = link_to(image_tag("edit_bar_btn2.png"), edit_venue_path(venue.id), :class => 'bar_btns', :remote => true)
      = link_to(image_tag("delete_bar_btn2.png"), "/venues/#{venue.id}", :class => 'bar_btns', :method => :delete, :remote => true, :confirm => "Are you sure you want to delete this venue?")
      = link_to(image_tag("avail_bar_btn2.png"), new_availabilities_venue_path(venue.id), :class => 'bar_btns', :remote => true)
  .row
    .large-12.columns
      %p= "Categories: #{venue.categories.map(&:name).join(", ")}"
  .row
    .large-12.columns
      / %h5.availabilities Availabilities
      .venue_availabilities{:data => {venue:venue.id}}
        = render :partial => 'venues/availabilities', :locals => {:venue => venue}
  %hr

app/views/venues/create.js.erb
$("#modal").empty().append("<%=j render 'venues/add_activity'%>");

app/views/venues/create_availabilities.js.erb
$("#modal").foundation("reveal", "close");
$(".venue_availabilities[data-venue=<%= @venue.id%>]").empty().append("<%=j render :partial => 'venues/availabilities', :locals => {:venue => @venue} %>");

app/views/venues/destroy.js.erb
$("#my_venues").empty().append("<%=j render 'venues/my_venues'%>");

app/views/venues/edit.js.erb
var a = $("<a>").addClass("close-reveal-modal").text("×");
$("#modal").empty().append("<%=j render 'venues/form' %>").append(a);
$("#modal").foundation("reveal", "open");
a.click(function(){$("#modal").foundation("reveal", "close");});

app/views/venues/new.js.erb
var a = $("<a>").addClass("close-reveal-modal").text("×");
$("#modal").empty().append("<%=j render 'venues/form' %>").append(a);
$("#modal").foundation("reveal", "open");
a.click(function(){$("#modal").foundation("reveal", "close");});

app/views/venues/new_availabilities.js.erb
var a = $("<a>").addClass("close-reveal-modal").text("×");
$("#modal").empty().append("<%=j render 'availabilities/form' %>").append(a);
$("#modal").foundation("reveal", "open");
$("#calendar").multiDatesPicker({
  dateFormat: "yy-mm-dd",
  altField: '#dates'
});
a.click(function(){$("#modal").foundation("reveal", "close");});

app/views/venues/update.js.erb
$("#modal").foundation("reveal", "close");
$("#my_venues").empty().append("<%=j render 'venues/my_venues'%>");