config/routes.rb
Barcode::Application.routes.draw do
  root :to => 'home#index'
  resources :users, :only => [:new, :create]
  resources :session, :only => [:new, :create] do
    collection do
      delete :destroy
    end
  end
  resources :venues, :except => [:index, :show] do
    member do
      get "new_availabilities"
      post "create_availabilities"
    end
  end
  resources :availabilities, :only => [:edit, :update, :destroy]
  resources :pub_crawls do
    collection do
      get "end_times"
      post "invite_friends"
    end
    member do
      post "join_crawl"
    end
  end
  resources :stops, :only => [:create] do
    collection do
      post "num_stops"
    end
  end
  resources :activities, :only => [:create, :new]
  resources :check_ins, :only => [:create, :new] do
    collection do
      get "select_location"
    end
  end
  resources :responses, :only => [:create, :new]
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    @activity = @cu.check_ins.last.stop.activity
  end

  def create
    stop = @cu.check_ins.last.stop
    if params[:text].nil?
      @cu.responses << Response.create(image:params[:image], stop_id:stop.id, response_type:"p")
    else
      @cu.responses << Response.create(text:params[:text], stop_id:stop.id, response_type:"t")
    end
    promotion = stop.venue.availabilities.where(:date => Date.today).first.promotion
    p = (1..10).to_a.shuffle.sample(3).join + promotion.upcase.gsub("!","").gsub(" ", "")
    client = Twilio::REST::Client.new(ENV['TW_SID'], ENV['TW_TOK'])
    body = "Congrats! You finished a challenge, here's your coupon code for #{promotion}: #{p}"
    client.account.sms.messages.create(:from => ENV['TW_NUM'], :to => @cu.phone, :body => body)
    if stop.next_stop.present?
      nxt = stop.next_stop
      daddress = nxt.venue.address.gsub(" ", "+")
      a = @cu.check_ins.last.latitude
      b = @cu.check_ins.last.longitude
      saddress = "#{a},#{b}"
      body = "Here are the directions to your next stop: http://maps.google.com/maps?daddr=#{daddress}&saddr=#{saddress}"
      client.account.sms.messages.create(:from => ENV['TW_NUM'], :to => @cu.phone, :body => body)
    else
      body = "Congrats! You finished your Pub Crawl!"
      client.account.sms.messages.create(:from => ENV['TW_NUM'], :to => @cu.phone, :body => body)
    end
  end
end

app/views/responses/_form.html.haml
#mobile_form
  -if @activity.response_type == "t"
    %p Your quesiton was:
    %p.lob= "#{@activity.text}"
    %p Enter your response below
    =form_tag responses_path, :remote => true do
      =hidden_field_tag :activity, @activity.id
      =text_area_tag :text
      =submit_tag nil, :class => "button round small"
  -else
    %p Your challenge was:
    %p.lob= "#{@activity.text}"
    %p Upload your photo as proof below
    =form_tag responses_path, :html => {:multipart => true}, :remote => true do
      =hidden_field_tag :activity, @activity.id
      #file=file_field_tag :image
      =submit_tag nil, :class => "button round small"

app/views/responses/_recieved.html.haml
#mobile_recieved
  %p.cab We got your response!

  -if @cu.responses.last.response_type == "t"
    %p#response_text= "#{@cu.responses.last.text}"
  -else
    #response_pic= image_tag(@cu.responses.last.image)

  %p Expect a text with your coupon and next location!
  =link_to("Log Out", session_index_path, :method => :delete, :class => "button round small", :id => "mobile_log_out_btn")

app/views/responses/create.js.erb
$("#mobile_content").empty().append("<%=j render 'responses/recieved' %>")

app/views/responses/new.js.erb
$("#mobile_content").empty().append("<%=j render 'responses/form' %>")