config/routes.rb
Barcode::Application.routes.draw do
  root :to => 'home#index'
  resources :users, :only => [:new, :create]
  resources :session, :only => [:new, :create] do
    collection do
      delete :destroy
    end
  end
  resources :venues, :except => [:index, :show] do
    member do
      get "new_availabilities"
      post "create_availabilities"
    end
  end
  resources :availabilities, :only => [:edit, :update, :destroy]
  resources :pub_crawls do
    collection do
      get "end_times"
      post "invite_friends"
    end
    member do
      post "join_crawl"
    end
  end
  resources :stops, :only => [:create] do
    collection do
      post "num_stops"
    end
  end
  resources :activities, :only => [:create, :new]
  resources :check_ins, :only => [:create, :new] do
    collection do
      get "select_location"
    end
  end
  resources :responses, :only => [:create, :new]
end

app/views/layouts/_body.html.haml
#desktop_nav.hide-for-touch
  -if @cu.nil?
    .row{style:"margin-top:3em;"}
      .large-12.columns
        .row
          .large-6.columns
            #register_c= link_to(image_tag("register_coaster2.png"), new_user_path, :class => 'login', :id => 'register_coaster', :remote => true)
          .large-6.columns
            #login_c= link_to(image_tag("login_coaster2.png"), new_session_path, :class => 'login', :id => 'login_coaster', :remote => true)
          / %img{:onmouseout => "this.src='/assets/login_coaster.jpg'", :onmouseover => "this.src='/assets/register_coaster.jpg'", :src => "/assets/login_coaster.jpg"}
  -else
    %ul.nav
      .row
        .large-2.columns
          %li.title
            =image_tag("barcode_logo_blue.png", :class => 'logo_img')
          %li
            =image_tag("barcode_text_blue.png", :class => 'logo_text')
            / %h3.logo BarCode
        .large-4.columns
        .large-6.columns.text-right
          = link_to(" #{@cu.name} | ", "#", :class => 'login_info')
          = link_to("Logout", session_index_path, :class => 'login_info', :method => :delete)


.row
  #mobile_nav.show-for-touch
    -if @cu.present?
      .row
        .small-7.columns
          #mobile_logo= link_to("BarCode", root_path)
        .small-5.columns{style:"text-align:right !important;"}
          #mobile_logout= link_to("Logout", session_index_path, :method => :delete)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BarCode</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <meta name="bitly-verification" content="77bec2b7e9fb"/>
  <%= favicon_link_tag 'barcode.ico' %>
</head>
<body>
<!--   <h1 style="padding-left: 20px;">BarCode</h1> -->
  <div id="nav_body"><%= render "layouts/body" %></div>

<%= yield %>


  <div id="modal" class="reveal-modal medium"></div>
</body>
</html>